language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
install:
  - cpanm -qn Dist::Zilla
  - dzil authordeps |cpanm -qn
  - dzil listdeps |cpanm -qn
script:
  - dzil test --all
